  ibv_srq = packed record
  end;

  ibv_mr = packed record
  end;

  ibv_sge = packed record
  end;

  ibv_recv_wr = packed record
  end;

  ibv_send_wr = packed record
  end;

  ibv_device = packed record
  end;

  ibv_context = packed record
  end;

  ibv_device_attr = packed record
  end;

  ibv_pd = packed record
  end;

  ibv_cq = packed record
  end;

  ibv_port_attr = packed record
  end;
