  Pmca_topo_base_component_t = ^mca_topo_base_component_t;
  Pmca_topo_base_comm_dist_graph_2_2_0_t = ^mca_topo_base_comm_dist_graph_2_2_0_t;
  Pmca_topo_base_comm_cart_2_2_0_t = ^mca_topo_base_comm_cart_2_2_0_t;
  Pmca_topo_base_comm_graph_2_2_0_t = ^mca_topo_base_comm_graph_2_2_0_t;
  Pmca_topo_base_module_t = ^mca_topo_base_module_t;
  
  Pmca_base_module_2_0_0_t = ^mca_base_module_2_0_0_t;
  
  Pmca_btl_openib_module_t = ^mca_btl_openib_module_t;
//  Pmca_btl_openib_qp_type_t = ^mca_btl_openib_qp_type_t;
  Pmca_btl_openib_proc_t = ^mca_btl_openib_proc_t;
  Pmca_btl_openib_proc_modex_t = ^mca_btl_openib_proc_modex_t;
  Pmca_btl_openib_send_control_frag_t = ^mca_btl_openib_send_control_frag_t;
  Pmca_btl_openib_reg_t = ^mca_btl_openib_reg_t;
  Pmca_btl_openib_header_t = ^mca_btl_openib_header_t;
  Pmca_btl_openib_footer_t = ^mca_btl_openib_footer_t;
  Pmca_btl_openib_qp_t = ^mca_btl_openib_qp_t;
  Pmca_btl_openib_endpoint_qp_t = ^mca_btl_openib_endpoint_qp_t;
  Pmca_btl_openib_device_t = ^mca_btl_openib_device_t;
  Pmca_btl_openib_module_qp_t = ^mca_btl_openib_module_qp_t;
  Pmca_btl_openib_recv_frag_t = ^mca_btl_openib_recv_frag_t;
  Pmca_btl_openib_rem_qp_info_t = ^mca_btl_openib_rem_qp_info_t;
  Pmca_btl_openib_rem_srq_info_t = ^mca_btl_openib_rem_srq_info_t;
  Pmca_btl_openib_device_qp_t = ^mca_btl_openib_device_qp_t;

  Pmca_btl_base_segment_t = ^mca_btl_base_segment_t;
  Pmca_btl_base_module_t = ^mca_btl_base_module_t;
  PPmca_btl_base_module_t = ^Pmca_btl_base_module_t;
  Pmca_btl_base_endpoint_t = ^mca_btl_base_endpoint_t;
  PPmca_btl_base_endpoint_t = ^Pmca_btl_base_endpoint_t;
  Pmca_btl_base_descriptor_t = ^mca_btl_base_descriptor_t;
  Pmca_btl_base_registration_handle_t = ^mca_btl_base_registration_handle_t;
  Pmca_btl_base_component_t = ^mca_btl_base_component_t;

  Popal_class_t	= ^opal_class_t;
  Popal_object_t = ^opal_object_t;
  Popal_hash_element_t = ^opal_hash_element_t;
  Popal_mutex_t	= ^opal_mutex_t;
  Popal_hash_type_methods_t = ^opal_hash_type_methods_t;
  Popal_list_item_t = ^opal_list_item_t;
  Popal_list_t = ^opal_list_t;
  Popal_convertor_t = ^opal_convertor_t;
  Popal_proc_t = ^opal_proc_t;
  Popal_bitmap_t = ^opal_bitmap_t;
  Popal_info_t = ^opal_info_t;
  Popal_free_list_item_t = ^opal_free_list_item_t;
  Popal_pointer_array_t = ^opal_pointer_array_t;

  Popal_btl_openib_connect_base_module_t = ^opal_btl_openib_connect_base_module_t;
  PPopal_btl_openib_connect_base_module_t = ^Popal_btl_openib_connect_base_module_t;
  Popal_btl_openib_connect_base_component_t = ^opal_btl_openib_connect_base_component_t;
  Popal_btl_openib_connect_base_module_data_t = ^opal_btl_openib_connect_base_module_data_t;
  

  Pompi_osc_base_module_t = ^ompi_osc_base_module_t;

  Pmca_mpool_base_module_t = ^mca_mpool_base_module_t;
  PPmca_mpool_base_module_t = ^Pmca_mpool_base_module_t;
  Pmca_mpool_base_component_t = ^mca_mpool_base_component_t;

  Pmca_rcache_base_module_t = ^mca_rcache_base_module_t;
  Pmca_rcache_base_registration_t = ^mca_rcache_base_registration_t;
  PPmca_rcache_base_registration_t = ^Pmca_rcache_base_registration_t;
  Pmca_rcache_base_component_t = ^mca_rcache_base_component_t;

  Pmca_coll_base_comm_coll_t = ^mca_coll_base_comm_coll_t;
  Pmca_coll_base_module_2_3_0_t = ^mca_coll_base_module_2_3_0_t;
  Pmca_coll_base_comm_t = ^mca_coll_base_comm_t;


  Pib_address_t = ^ib_address_t;